apiVersion: v1
kind: Service
metadata:
  name: product-microservice-service
spec:
  type: ClusterIP
  selector:
    app: product-microservice
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
